event_registration.settings:
  type: config_object
  label: 'Event Registration settings'
  mapping:
    admin_email:
      type: email
      label: 'Admin notification email'
    enable_admin_notification:
      type: boolean
      label: 'Enable admin notifications'
    enable_user_notification:
      type: boolean
      label: 'Enable user confirmation emails'
    site_name_in_email:
      type: string
      label: 'Site name for emails'
